<?php

print "<!doctype html>\n";
print "<html>\n";
print "  <head>\n";
print "    <meta charset=\"utf-8\">\n";
print "    <meta name=\"viewport\" content=\"width=device-width\">\n";
print "    <meta name=\"description\" content=\"| Nicholas Minor | Digital Artist | BFA University of Nevada |\">\n";
print "	  <meta name=\"keywords\" content=\"Nicholas, Minor, Nicholas Minor, nicholasminor.computer, BFA, Nevada, UNR, Art, Digital Art, Nicholas Human, nicholas_human, nicholas.human, Nick Minor, nick minor, nick minor art, nicholas minor art, nick, minor, nickminor.computer, .computer, nick.computer, minor.computer\">\n";
print "  	<meta name=\"author\" content=\"Nicholas Minor\">\n";
print "    <title>artist | NicholasMinor.computer | artist</title>\n";
print "    <link rel=\"stylesheet\" href=\"./css/style.css\">\n";
print "  </head>\n";
print "  <body>\n";
print "        <header id=\"top\">\n";
print "          <div class=\"container\">\n";
print "            <div id=\"top\">\n";
print "              <nav class=\"top\">\n";
print "                <ul>\n";
print "                  <li><a href=\"index.html\">home</a></li>\n";
print "                  <li><a href=\"portfolio.html\">portfolio</a></li>\n";
print "                  <li><a href=\"about.html\">about</a></li>\n";
print "                  <li><a href=\"cv.html\">cv</a></li>\n";
print "                  <li><a href=\"contact.html\">contact</a></li>\n";
print "                </ul>\n";
print "              </nav>\n";
print "            </div>\n";
print "          </div>\n";
print "        </div>\n";
print "        </header>\n";
print "\n";
print "      <section id=\"name\">\n";
print "        <header id=\"name\">\n";
print "          <div class=\"container\">\n";
print "            <nav class=\"name\">\n";
print "              <h1 id=\"name\"><a href=\"about.html\">    Nicholas    </a></h1>\n";
print "              <h1 id=\"name\"><a href=\"about.html\">    Minor    </a></h1>\n";
print "            </nav>\n";
print "          </div>\n";
print "        </header>\n";
print "      </section>\n";
print "\n";
print "      <section id=\"showcase\">\n";
print "        <div class=\"container\">\n";
print "              <nav class=\"showcasehead\">\n";
print "                  <h1 id=artist><a href=\"about.html\"><br> ARTIST ARTIST ARTIST ARTIST ARTIST ARTIST ARTIST ARTIST ARTIST</a></h1>\n";
print "              </nav>\n";
print "\n";
print "        <div id=work>\n";
print "          <p id=\"work\"><a href=\"portfolio.html\">=work</a></p>\n";
print "        </div>\n";
print "\n";
print "              <nav class=\"showcasesubhead\">\n";
print "                    <h1 id=\"ongoing\"><a href=\"ongoing.html\">ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING ONGOING </a></h1>\n";
print "              </nav>\n";
print "        </div>\n";
print "        <div class=\"container\" id =\"homebody\">\n";
print "          <body id=\"showcasebody\">\n";
print "\n";
print "            <p id=homebody>UNDER CONSTRUCTION</p>\n";
print "\n";
print "          </body>\n";
print "        </div>\n";
print "      </section>\n";
print "\n";
print "      <header id=\"low\">\n";
print "        <div class=\"container\">\n";
print "          <div id=\"low\">\n";
print "            <nav class=\"low\">\n";
print "              <ul>\n";
print "                <li><a href=\"idex.html\">home</a></li>\n";
print "                <li><a href=\"portfolio.html\">portfolio</a></li>\n";
print "                <li><a href=\"about.html\">about</a></li>\n";
print "                <li><a href=\"cv.html\">cv</a></li>\n";
print "                <li><a href=\"contact.html\">contact</a></li>\n";
print "              </ul>\n";
print "            </nav>\n";
print "          </div>\n";
print "        </div>\n";
print "      </header>\n";
print "\n";
print "      <footer id=\"footer\">\n";
print "        <div class=\"container\">\n";
print "          <p id=\"copyright\">nicholasminor.computer copyright © 2017 fuck off</p>\n";
print "        </div>\n";
print "      </footer>\n";
print "\n";
print "\n";
print "</body>\n";
print "</html>";

?>
